dependencies:
  certificate_roots:
    url: github.com/toitware/toit-cert-roots
    version: ^1.3.2
  dht11:
    url: github.com/nilwes/DHT11
    version: ^1.1.0
  dhtxx:
    path: /home/flo/code/toit-dhtxx
  ds18b20:
    url: github.com/toitware/toit-ds18b20
    version: ^1.0.1
  hc_sr04:
    url: github.com/lask/toit-hc-sr04
    version: ^1.2.0
  http:
    url: github.com/toitlang/pkg-http
    version: ^1.9.0
  ntp:
    url: github.com/toitlang/pkg-ntp
    version: ^1.0.0
  one_wire:
    url: github.com/toitware/toit-1-wire
    version: ^1.2.0
  pictogrammers_icons:
    url: github.com/toitware/toit-icons-pictogrammers
    version: ^1.0.0
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
  pixel_strip:
    url: github.com/toitware/toit-pixel-strip
    version: ^0.1.1
  servo:
    url: github.com/andersjohnsen/servo
    version: ^1.1.0
  ssd1306:
    url: github.com/toitware/toit-ssd1306
    version: ^1.4.0
